/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.Cita;
import Logic.Logic;
import Logic.Roles;
import Logic.logicaPilaFiles;
import Logic.pilaNodo;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class CitaCliente extends javax.swing.JFrame {

    /**
     * Creates new form CitaCliente
     */
    public CitaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbmHora = new javax.swing.JComboBox<>();
        btnSolicitar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 1500));
        getContentPane().setLayout(null);

        txtCedula.setEditable(false);
        getContentPane().add(txtCedula);
        txtCedula.setBounds(180, 110, 171, 26);

        jLabel3.setText("Hora:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 170, 40, 20);

        cbmHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8 a.m", "9 a.m", "10 a.m", "11 a.m", "2 p.m", "3 p.m", "4 p.m", "5 p.m", " " }));
        getContentPane().add(cbmHora);
        cbmHora.setBounds(180, 170, 79, 26);

        btnSolicitar.setText("Solicitar");
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitar);
        btnSolicitar.setBounds(310, 230, 112, 29);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(470, 60, 160, 26);

        jLabel2.setText("Fecha: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 60, 51, 20);

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(0, 10, 80, 29);

        lblNombre.setText("Nombre del Paciente: ");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(10, 60, 160, 24);

        jLabel1.setText("Cédula:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 110, 54, 20);

        jTextField1.setEditable(false);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 60, 76, 26);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   Main uR = new Main();
    logicaPilaFiles stack = new logicaPilaFiles();
    Logic Stack = new Logic();
   
     public void mostrarNombre(){
        Logic lC = new Logic();
        ArrayList<Roles> array = new ArrayList();
        
        Roles tempCountries[] = lC.readRegistersFilesIndividual();
        for(int i = 0; i < tempCountries.length; i++){
            array.add(tempCountries[i]);
        }//endfor
        for (int j = 0; j < 1; j++) {
            txtCedula.setText(array.get(j).getCedula().trim());
        jTextField1.setText(array.get(j).getNombre().trim());
        
        }
    } 
 
    
    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        //Campos vacios validacion
        String dia=Integer.toString(jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes=Integer.toString(jDateChooser1.getCalendar().get(Calendar.MONTH)+1);
        String year=Integer.toString(jDateChooser1.getCalendar().get(Calendar.YEAR));
        String fecha=(year+"-"+mes+"-"+dia);

        if (txtCedula.getText().equals("") || jTextField1.getText().equals("") || cbmHora.getSelectedItem().equals("") || jDateChooser1.getDate().equals("")) {
            JOptionPane.showMessageDialog(null, "Rellene todos los espacios en blanco");
        }//End if
        else {
            if(Stack.searchCita(fecha, cbmHora.getSelectedItem().toString()) == false){
                pilaNodo pila = new pilaNodo();
                Cita cita = new Cita(fecha, cbmHora.getSelectedItem().toString(), txtCedula.getText(), jTextField1.getText());
                pila.push(fecha,cbmHora.getSelectedItem().toString(), jTextField1.getText(), txtCedula.getText());
                stack.insertCita(cita);
                JOptionPane.showMessageDialog(null, "Cita Registrada");
            } else {
                JOptionPane.showMessageDialog(null, "La hora y fecha que solicita se encuentran ocupadas");
            }
        }

        //else
        //           JOptionPane.showMessageDialog(null, "Cita NO Registrada");
    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Customer nS = new Customer();
        nS.setVisible (true);
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        mostrarNombre();
    }//GEN-LAST:event_jTextField1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JComboBox<String> cbmHora;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
