/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author HELLO
 */
public class CreateCustomer extends javax.swing.JFrame {

    /**
     * Creates new form CreateCustomer
     */
    public CreateCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCreateCustomer = new javax.swing.JLabel();
        lbUserNameCustomer = new javax.swing.JLabel();
        lbPasswordCustomer = new javax.swing.JLabel();
        tfUserNameCustomer = new javax.swing.JTextField();
        pSCustomer = new javax.swing.JPasswordField();
        lbNameCustomer = new javax.swing.JLabel();
        lbLastNameCustomer = new javax.swing.JLabel();
        lbAgeCustomer = new javax.swing.JLabel();
        lbEmailCustomer = new javax.swing.JLabel();
        lbPhoneCustomer = new javax.swing.JLabel();
        tfNameCustomer = new javax.swing.JTextField();
        tfLastNameCustomer = new javax.swing.JTextField();
        tfAgeCustomer = new javax.swing.JTextField();
        tfEmailCustomer = new javax.swing.JTextField();
        tfPhoneCustomer = new javax.swing.JTextField();
        btnAddNewCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbCreateCustomer.setText("CREATE CUSTOMER");

        lbUserNameCustomer.setText("USERNAME:");

        lbPasswordCustomer.setText("PASSWORD:");

        lbNameCustomer.setText("NAME:");

        lbLastNameCustomer.setText("LAST NAME:");

        lbAgeCustomer.setText("AGE:");

        lbEmailCustomer.setText("EMAIL:");

        lbPhoneCustomer.setText("PHONE:");

        tfPhoneCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneCustomerActionPerformed(evt);
            }
        });

        btnAddNewCustomer.setText("ADD NEW CUSTOMER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(lbCreateCustomer)
                .addGap(256, 256, 256))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUserNameCustomer)
                    .addComponent(lbPasswordCustomer)
                    .addComponent(lbNameCustomer)
                    .addComponent(lbLastNameCustomer)
                    .addComponent(lbAgeCustomer)
                    .addComponent(lbEmailCustomer)
                    .addComponent(lbPhoneCustomer))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddNewCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfUserNameCustomer)
                        .addComponent(pSCustomer)
                        .addComponent(tfNameCustomer)
                        .addComponent(tfLastNameCustomer)
                        .addComponent(tfAgeCustomer)
                        .addComponent(tfEmailCustomer)
                        .addComponent(tfPhoneCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbCreateCustomer)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNameCustomer)
                    .addComponent(tfNameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLastNameCustomer)
                    .addComponent(tfLastNameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAgeCustomer)
                    .addComponent(tfAgeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUserNameCustomer)
                    .addComponent(tfUserNameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPasswordCustomer)
                    .addComponent(pSCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmailCustomer)
                    .addComponent(tfEmailCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPhoneCustomer)
                    .addComponent(tfPhoneCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnAddNewCustomer)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPhoneCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCustomer;
    private javax.swing.JLabel lbAgeCustomer;
    private javax.swing.JLabel lbCreateCustomer;
    private javax.swing.JLabel lbEmailCustomer;
    private javax.swing.JLabel lbLastNameCustomer;
    private javax.swing.JLabel lbNameCustomer;
    private javax.swing.JLabel lbPasswordCustomer;
    private javax.swing.JLabel lbPhoneCustomer;
    private javax.swing.JLabel lbUserNameCustomer;
    private javax.swing.JPasswordField pSCustomer;
    private javax.swing.JTextField tfAgeCustomer;
    private javax.swing.JTextField tfEmailCustomer;
    private javax.swing.JTextField tfLastNameCustomer;
    private javax.swing.JTextField tfNameCustomer;
    private javax.swing.JTextField tfPhoneCustomer;
    private javax.swing.JTextField tfUserNameCustomer;
    // End of variables declaration//GEN-END:variables
}
