/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.Logic;
import Logic.Delete;
import Logic.Roles;
import Logic.Update;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pc
 */
public class CRUD extends javax.swing.JFrame {

    /**
     * Creates new form CRUD
     */
     FondoPanel fondo = new FondoPanel();
    public CRUD() {
        this.setContentPane(fondo);
        initComponents();
        this.setExtendedState(CRUD.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnshowRoles = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        tfUserName = new javax.swing.JTextField();
        tfAge = new javax.swing.JTextField();
        tfPhone = new javax.swing.JTextField();
        lbLastName = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        lbAge = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lbID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lbRol = new javax.swing.JLabel();
        tfRol = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        lbMensajes = new javax.swing.JLabel();
        cbReportes = new javax.swing.JComboBox<>();
        lbReports = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "LAST NAME", "USERNAME", "PASSWORD", "AGE", "PHONE", "EMAIL", "ROL"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);

        jScrollPane3.setBounds(1070, 40, 600, 440);

        jScrollPane3.setBounds(260, 30, 603, 447);


        btnshowRoles.setText("SHOW ROLES");
        btnshowRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowRolesActionPerformed(evt);
            }
        });
        getContentPane().add(btnshowRoles);

        btnshowRoles.setBounds(1100, 550, 170, 32);

        btnshowRoles.setBounds(260, 510, 99, 23);


        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);

        btnDelete.setBounds(1440, 550, 110, 32);
        getContentPane().add(tfName);
        tfName.setBounds(880, 100, 150, 30);

        lbName.setText("NAME");
        getContentPane().add(lbName);
        lbName.setBounds(880, 70, 40, 20);
        getContentPane().add(tfLastName);
        tfLastName.setBounds(880, 180, 150, 30);
        getContentPane().add(tfUserName);
        tfUserName.setBounds(880, 260, 150, 30);
        getContentPane().add(tfAge);
        tfAge.setBounds(880, 410, 150, 30);

        btnDelete.setBounds(490, 510, 69, 23);
        getContentPane().add(tfName);
        tfName.setBounds(50, 140, 140, 20);

        lbName.setText("NAME");
        getContentPane().add(lbName);
        lbName.setBounds(50, 110, 28, 14);
        getContentPane().add(tfLastName);
        tfLastName.setBounds(50, 220, 140, 20);
        getContentPane().add(tfUserName);
        tfUserName.setBounds(50, 290, 140, 20);
        getContentPane().add(tfAge);
        tfAge.setBounds(50, 430, 140, 20);


        tfPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(tfPhone);

        tfPhone.setBounds(880, 470, 150, 30);

        lbLastName.setText("LAST NAME");
        getContentPane().add(lbLastName);
        lbLastName.setBounds(880, 150, 70, 20);

        lbUserName.setText("USERNAME");
        getContentPane().add(lbUserName);
        lbUserName.setBounds(880, 230, 70, 20);

        lbAge.setText("AGE");
        getContentPane().add(lbAge);
        lbAge.setBounds(880, 380, 30, 20);

        lbPhone.setText("PHONE");
        getContentPane().add(lbPhone);
        lbPhone.setBounds(880, 450, 50, 20);

        tfPhone.setBounds(50, 500, 140, 20);

        lbLastName.setText("LAST NAME");
        getContentPane().add(lbLastName);
        lbLastName.setBounds(50, 190, 55, 14);

        lbUserName.setText("USERNAME");
        getContentPane().add(lbUserName);
        lbUserName.setBounds(50, 260, 54, 14);

        lbAge.setText("AGE");
        getContentPane().add(lbAge);
        lbAge.setBounds(50, 400, 20, 14);

        lbPhone.setText("PHONE");
        getContentPane().add(lbPhone);
        lbPhone.setBounds(50, 470, 34, 14);


        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);

        btnUpdate.setBounds(1300, 550, 110, 32);

        lbID.setText("ID");
        getContentPane().add(lbID);
        lbID.setBounds(880, 10, 20, 20);
        getContentPane().add(tfID);
        tfID.setBounds(880, 40, 150, 30);

        lbEmail.setText("EMAIL");
        getContentPane().add(lbEmail);
        lbEmail.setBounds(880, 510, 40, 20);
        getContentPane().add(tfEmail);
        tfEmail.setBounds(880, 540, 150, 30);

        lbRol.setText("ROL");
        getContentPane().add(lbRol);
        lbRol.setBounds(880, 580, 30, 20);
        getContentPane().add(tfRol);
        tfRol.setBounds(880, 610, 150, 30);

        lbPassword.setText("PASSWORD");
        getContentPane().add(lbPassword);
        lbPassword.setBounds(880, 310, 80, 20);
        getContentPane().add(tfPassword);
        tfPassword.setBounds(880, 340, 150, 30);

        btnUpdate.setBounds(390, 510, 71, 23);

        lbID.setText("ID");
        getContentPane().add(lbID);
        lbID.setBounds(50, 40, 11, 14);
        getContentPane().add(tfID);
        tfID.setBounds(50, 70, 140, 20);

        lbEmail.setText("EMAIL");
        getContentPane().add(lbEmail);
        lbEmail.setBounds(50, 540, 30, 14);
        getContentPane().add(tfEmail);
        tfEmail.setBounds(50, 570, 140, 20);

        lbRol.setText("ROL");
        getContentPane().add(lbRol);
        lbRol.setBounds(50, 610, 20, 14);
        getContentPane().add(tfRol);
        tfRol.setBounds(50, 640, 140, 20);

        lbPassword.setText("PASSWORD");
        getContentPane().add(lbPassword);
        lbPassword.setBounds(50, 330, 57, 14);
        getContentPane().add(tfPassword);
        tfPassword.setBounds(50, 360, 140, 20);

        getContentPane().add(lbMensajes);
        lbMensajes.setBounds(1070, 510, 350, 28);

        cbReportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF", "EXCEL" }));
        getContentPane().add(cbReportes);
        cbReportes.setBounds(760, 510, 110, 20);

        lbReports.setText("EXPORT REPORTS");
        getContentPane().add(lbReports);
        lbReports.setBounds(770, 490, 110, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int seleccion = jTable3.getSelectedRow();
        tfID.setText(jTable3.getValueAt(seleccion, 0).toString());
        tfName.setText(jTable3.getValueAt(seleccion, 1).toString());
        tfLastName.setText(jTable3.getValueAt(seleccion, 2).toString());
        tfUserName.setText(jTable3.getValueAt(seleccion,3).toString());
        tfPassword.setText(jTable3.getValueAt(seleccion, 4).toString());
        tfAge.setText(jTable3.getValueAt(seleccion, 5).toString());
        tfPhone.setText(jTable3.getValueAt(seleccion, 6).toString());
        tfEmail.setText(jTable3.getValueAt(seleccion, 7).toString());
        tfRol.setText(jTable3.getValueAt(seleccion, 8).toString());
    }//GEN-LAST:event_jTable3MouseClicked

    private void btnshowRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowRolesActionPerformed

        mostrarRegistros();

    }//GEN-LAST:event_btnshowRolesActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
          try {
        Delete em = new Delete();
        int d = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO DELETE " + tfID.getText()+ " ?");
        if (d == 0) {
          
            em.removeLines(tfID.getText());
            lbMensajes.setText("SUCCESSFULLY REMOVED!");
            mostrarRegistros();
            tfID.setText("");
            tfName.setText("");
            tfLastName.setText("");
            tfUserName.setText("");
            tfPassword.setText("");
            tfAge.setText("");
            tfPhone.setText("");
            tfEmail.setText("");
            tfRol.setText("");
            
        }
            }catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "DELETE ERROR!");
            }   
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        try {
            Logic lC = new Logic();
            ArrayList<Roles> array = new ArrayList();
            String contraseña = "";

            Roles tempCustomers[] = lC.readRegistersFiles();
            for (int i = 0; i < tempCustomers.length; i++) {
                array.add(tempCustomers[i]);
            }//endfor

            for (int j = 0; j < array.size(); j++) {
                if (tfName.getText().equals(array.get(j).getNombre())) {
                    contraseña = array.get(j).getContraseña();
                }
            }

            Update em = new Update();
            int edit = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO UPDATE " + tfID.getText()+ " ?");
            if (edit == 0) {
                em.actualizarPersona(tfID.getText(), tfName.getText(), tfLastName.getText(),tfUserName.getText(), tfPassword.getText(),Integer.parseInt(tfAge.getText()), Integer.parseInt(tfPhone.getText()),tfEmail.getText(), Integer.parseInt(tfRol.getText()));
                lbMensajes.setText("SUCCESSFULLY UPDATED!");
                mostrarRegistros();
                tfID.setText("");
                tfName.setText("");
                tfLastName.setText("");
                tfUserName.setText("");
                tfPassword.setText("");
                tfAge.setText("");
                tfPhone.setText(""); 
                tfEmail.setText("");
                tfRol.setText("");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "UPDATE ERROR!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tfPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneActionPerformed

    public void mostrarRegistros() {
        Logic lC = new Logic();
        ArrayList<Roles> array = new ArrayList();

        Roles tempCustomers[] = lC.readRegistersFiles();
        for (int i = 0; i < tempCustomers.length; i++) {
            array.add(tempCustomers[i]);
        }//endfor

        String matriz[][] = new String[array.size()][9];

        for (int i = 0; i < array.size(); i++) {
            int edad = array.get(i).getEdad();
            int tipoRol = array.get(i).getTipoRol();
            int telefono = array.get(i).getTelefono();
            
            matriz[i][0] = array.get(i).getCedula();
            matriz[i][1] = array.get(i).getNombre();
            matriz[i][2] = array.get(i).getApellido();
            matriz[i][3] = array.get(i).getNombreUsuario();
            matriz[i][4] = array.get(i).getContraseña();
            matriz[i][5] = String.valueOf(edad);
            matriz[i][6] = String.valueOf(telefono);
            matriz[i][7] = array.get(i).getCorreo();
            matriz[i][8] = String.valueOf(tipoRol);

            jTable3.setModel(new javax.swing.table.DefaultTableModel(
                    matriz,
                    new String[]{
                        "ID", "NAME", "LAST NAME", "USERNAME", "PASSWORD","AGE", "PHONE","EMAIL","ROL"
                    }
            ));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnshowRoles;
    private javax.swing.JComboBox<String> cbReportes;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable3;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbMensajes;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbReports;
    private javax.swing.JLabel lbRol;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfRol;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables

     class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {

            imagen = new ImageIcon(getClass().getResource("/Images/frutas5.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);

            super.paint(g);
        }
    }
}
