package GUI;

import java.io.IOException;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Logic.Logic;
import Logic.NotasCliente;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Logic.ColaMetodos;
import Logic.ColaFilesLog;
import Logic.Delete;
import Logic.ExportarExcel;
import Logic.Update;
import java.awt.print.PrinterException;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JTable;

/**
 *
 * @author pc
 */
public class CRUDNotes extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_NOTAS
     */
    public CRUDNotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableNotes = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        txtMuscular = new javax.swing.JTextField();
        txtGrasa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCorporal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtAgua = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaNotas = new javax.swing.JTextArea();
        btnMostrar = new javax.swing.JButton();
        btnBorrarEspecifico = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jLabel7.setText("NOTAS REGISTRADAS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(422, 18, 199, 37);
        getContentPane().add(txtBuscar);
        txtBuscar.setBounds(375, 77, 222, 26);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(615, 76, 79, 29);

        jTableNotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Paciente", "Notas", "Peso", "M. Muscular", "% Grasa", "Altura", "Edad", "M. Corporal", "% Agua", "Fecha"
            }
        ));
        jTableNotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNotesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableNotes);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(35, 123, 803, 163);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(864, 174, 153, 29);

        btnEliminar.setText("Eliminar Paciente");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(864, 221, 153, 29);

        jLabel1.setText("Paciente:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(55, 318, 64, 20);

        txtCedula.setEditable(false);
        getContentPane().add(txtCedula);
        txtCedula.setBounds(137, 359, 121, 26);

        jLabel2.setText("Cédula:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(55, 362, 54, 20);
        getContentPane().add(txtAltura);
        txtAltura.setBounds(570, 315, 121, 26);

        jLabel3.setText("Notas:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(55, 403, 46, 20);

        jLabel4.setText("Peso:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(291, 318, 39, 20);

        jLabel5.setText("M. Muscular:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(291, 362, 90, 20);

        jLabel6.setText("% Grasa:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(291, 403, 67, 20);

        txtPaciente.setEditable(false);
        getContentPane().add(txtPaciente);
        txtPaciente.setBounds(137, 315, 121, 26);
        getContentPane().add(txtMuscular);
        txtMuscular.setBounds(396, 359, 121, 26);
        getContentPane().add(txtGrasa);
        txtGrasa.setBounds(364, 403, 121, 26);

        jLabel8.setText("Altura:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(503, 318, 49, 20);

        jLabel9.setText("Edad:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(532, 362, 41, 20);

        jLabel10.setText("M. Corporal:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(532, 406, 89, 20);
        getContentPane().add(txtPeso);
        txtPeso.setBounds(348, 315, 121, 26);
        getContentPane().add(txtEdad);
        txtEdad.setBounds(588, 359, 121, 26);
        getContentPane().add(txtCorporal);
        txtCorporal.setBounds(636, 403, 121, 26);

        jLabel11.setText("% Agua:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(709, 318, 64, 20);

        lblFecha.setText("Fecha:");
        getContentPane().add(lblFecha);
        lblFecha.setBounds(739, 362, 46, 20);
        getContentPane().add(txtAgua);
        txtAgua.setBounds(788, 315, 121, 26);

        txtFecha.setEditable(false);
        getContentPane().add(txtFecha);
        txtFecha.setBounds(800, 359, 121, 26);

        txtAreaNotas.setColumns(20);
        txtAreaNotas.setRows(5);
        jScrollPane1.setViewportView(txtAreaNotas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(119, 403, 166, 96);

        btnMostrar.setText("Mostrar Notas");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(864, 268, 153, 29);

        btnBorrarEspecifico.setText("Eliminar Nota");
        btnBorrarEspecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarEspecificoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrarEspecifico);
        btnBorrarEspecifico.setBounds(735, 23, 129, 29);

        jToggleButton1.setText("PDF");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(50, 30, 61, 29);

        jToggleButton2.setText("Excel");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(180, 30, 141, 29);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableNotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNotesMouseClicked
        int seleccion = jTableNotes.getSelectedRow();
        txtCedula.setText(jTableNotes.getValueAt(seleccion, 0).toString());
        txtPaciente.setText(jTableNotes.getValueAt(seleccion, 1).toString());
        txtAreaNotas.setText(jTableNotes.getValueAt(seleccion, 2).toString());
        txtPeso.setText(jTableNotes.getValueAt(seleccion, 3).toString());
        txtMuscular.setText(jTableNotes.getValueAt(seleccion, 4).toString());
        txtGrasa.setText(jTableNotes.getValueAt(seleccion, 5).toString());
        txtAltura.setText(jTableNotes.getValueAt(seleccion, 6).toString());
        txtEdad.setText(jTableNotes.getValueAt(seleccion, 7).toString());
        txtCorporal.setText(jTableNotes.getValueAt(seleccion, 8).toString());
        txtAgua.setText(jTableNotes.getValueAt(seleccion, 9).toString());
        txtFecha.setText(jTableNotes.getValueAt(seleccion, 10).toString());
    }//GEN-LAST:event_jTableNotesMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         try {
                Delete em = new Delete();
                int d = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar " + txtPaciente.getText() + " de este archivo?");
                if(d == 0){
                    em.removeLinesColaGeneral(txtCedula.getText());
                    mostrarNotas();
                    JOptionPane.showMessageDialog(null, "ELIMINADO CON EXITO");
                    
                    txtCedula.setText("");
                    txtPaciente.setText("");
                    txtAgua.setText("");
                    txtAltura.setText("");
                    txtAreaNotas.setText("");
                    txtBuscar.setText("");
                    txtCorporal.setText("");
                    txtEdad.setText("");
                    txtFecha.setText("");
                    txtGrasa.setText("");
                    txtMuscular.setText("");
                    txtPeso.setText("");
                }
            }catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al eliminar");
            }   
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        mostrarNotas();
        txtPaciente.setText("");
        txtAgua.setText("");
        txtAltura.setText("");
        txtAreaNotas.setText("");
        txtBuscar.setText("");
        txtCorporal.setText("");
        txtEdad.setText("");
        txtFecha.setText("");
        txtGrasa.setText("");
        txtMuscular.setText("");
        txtPeso.setText("");
        txtCedula.setText("");
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ColaFilesLog fl = new ColaFilesLog();
        if(fl.readingFiles(txtBuscar.getText()) == true){          
            try {
                searchClienteIndividual(txtBuscar.getText());
                txtBuscar.setText("");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CRUDNotes.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else{
        JOptionPane.showMessageDialog(null, "NO ENCONTRADO");}
        txtPaciente.setText("");
        txtAgua.setText("");
        txtAltura.setText("");
        txtAreaNotas.setText("");
        txtBuscar.setText("");
        txtCorporal.setText("");
        txtEdad.setText("");
        txtFecha.setText("");
        txtGrasa.setText("");
        txtMuscular.setText("");
        txtPeso.setText("");
        txtCedula.setText("");       
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBorrarEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarEspecificoActionPerformed
        
    }//GEN-LAST:event_btnBorrarEspecificoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
                Update em = new Update();
                int edit = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea modificar la cita de " + txtPaciente.getText() + " ?");
                if(edit == 0){
                    em.actualizarNotaPersona(txtCedula.getText(), txtPaciente.getText(), txtAreaNotas.getText(), Double.parseDouble(txtPeso.getText()), Double.parseDouble(txtMuscular.getText()), 
                            Double.parseDouble(txtGrasa.getText()), Double.parseDouble(txtAltura.getText()), Integer.parseInt(txtEdad.getText()), Double.parseDouble(txtCorporal.getText()), Double.parseDouble(txtAgua.getText()), txtFecha.getText());
                    JOptionPane.showMessageDialog(null, "MODIFICADO CON EXITO");
                    mostrarNotas();
                    txtCedula.setText("");
                    txtPaciente.setText("");
                    txtAgua.setText("");
                    txtAltura.setText("");
                    txtAreaNotas.setText("");
                    txtBuscar.setText("");
                    txtCorporal.setText("");
                    txtEdad.setText("");
                    txtFecha.setText("");
                    txtGrasa.setText("");
                    txtMuscular.setText("");
                    txtPeso.setText("");
                }
            }catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al modificar");
            }   
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        MessageFormat header=new MessageFormat("Registro de citas");
        MessageFormat footer=new MessageFormat("Page{0,number,integer}");
        try{
            jTableNotes.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (PrinterException ex) {
            System.err.format("error de impresion", ex.getMessage());
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed
void impresion() {
        JFileChooser seleccionar = new JFileChooser();
        File archivo;
        if (seleccionar.showDialog(null, "Exportar Excel") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();
            String imagen = archivo + ".xls";
            File file = new File(imagen);
            ExportarExcel excel = new ExportarExcel(jTableNotes, file, "" + "tablaimporte");
            excel.export(); 
        }
    }
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        impresion();
    }//GEN-LAST:event_jToggleButton2ActionPerformed
        
         //Busca al cliente en los registros si lo encuentra lo va a mostra en la tabla
    public void searchClienteIndividual(String cedula) throws FileNotFoundException{
        Logic lC = new Logic();
        ArrayList <NotasCliente> individual = new ArrayList();
        
        NotasCliente tempCountries[] = lC.readRegistersFilesNotas();
        for (int i = 0; i < tempCountries.length; i++) {
            if (tempCountries[i].getCedula().equalsIgnoreCase(cedula)){
                individual.add(tempCountries[i]);
            } 
        }

        String matriz[][]= new String[individual.size()][11];
        
        for (int i = 0; i < individual.size(); i++) {
            
        int edad = individual.get(i).getEdad();
        double peso = individual.get(i).getPeso();
        double musculo = individual.get(i).getMusculo();
        double grasa = individual.get(i).getGrasa();
        double altura = individual.get(i).getAltura();
        double masaCorporal = individual.get(i).getMasaCorporal();
        double agua = individual.get(i).getAgua();
        
        matriz[i][0]= individual.get(i).getCedula();
        matriz[i][1]= individual.get(i).getNombre();
        matriz[i][2]= individual.get(i).getNotas();
        matriz[i][3]= String.valueOf(peso);
        matriz[i][4]= String.valueOf(musculo);
        matriz[i][5]= String.valueOf(grasa);
        matriz[i][6]= String.valueOf(altura);
        matriz[i][7]= String.valueOf(edad);
        matriz[i][8]= String.valueOf(masaCorporal);
        matriz[i][9]= String.valueOf(agua);
        matriz[i][10]= individual.get(i).getFecha();
        
        jTableNotes.setModel(new javax.swing.table.DefaultTableModel(
           matriz,
            new String [] {
                "Cedula","Paciente", "Notas", "Peso", "M.Musculo", "% Grasa", "Altura", "Edad", "M.Corporal", "% Agua", "Fecha"
            }
        ));
        }   
    }

        public void mostrarNotas(){
        Logic lC = new Logic();
        ArrayList<NotasCliente> array = new ArrayList();
        
        NotasCliente tempCountries[] = lC.readRegistersFilesNotas();
        for(int i = 0; i < tempCountries.length; i++){
            array.add(tempCountries[i]);
        }//endfor
       
       String matriz[][]= new String[array.size()][11];
       
         for (int i = 0; i < array.size(); i++) {
        int edad = array.get(i).getEdad();
        double peso = array.get(i).getPeso();
        double musculo = array.get(i).getMusculo();
        double grasa = array.get(i).getGrasa();
        double altura = array.get(i).getAltura();
        double masaCorporal = array.get(i).getMasaCorporal();
        double agua = array.get(i).getAgua();
        
        matriz[i][0]= array.get(i).getCedula();
        matriz[i][1]= array.get(i).getNombre();
        matriz[i][2]= array.get(i).getNotas();
        matriz[i][3]= String.valueOf(peso);
        matriz[i][4]= String.valueOf(musculo);
        matriz[i][5]= String.valueOf(grasa);
        matriz[i][6]= String.valueOf(altura);
        matriz[i][7]= String.valueOf(edad);
        matriz[i][8]= String.valueOf(masaCorporal);
        matriz[i][9]= String.valueOf(agua);
        matriz[i][10]= array.get(i).getFecha();
        jTableNotes.setModel(new javax.swing.table.DefaultTableModel(
           matriz,
            new String [] {
                "Cedula","Paciente", "Notas", "Peso", "M.Musculo", "% Grasa", "Altura", "Edad", "M.Corporal", "% Agua", "Fecha"
            }
        ));
         } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDNotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarEspecifico;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTableNotes;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JTextField txtAgua;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextArea txtAreaNotas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorporal;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtGrasa;
    private javax.swing.JTextField txtMuscular;
    private javax.swing.JTextField txtPaciente;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
